### ISSUE TITLE
OwnHomeData?

### ISSUE THREAD

**Issue by daniillnull** [RostikDevBs/BrawlStarsServer#1]
Server doesn't send OwnHomeData. Game wants to get OwnHomeData after LoginOk but gets nothing. Where's OwnHomeData in your source code? You should implement OwnHomeData as soon as possible to make game work. OwnHomeData is required, please don't forget about it anymore. Thanks for adding OwnHomeData.

**Comment by RostikDevBs** [comment]
unfortunately OwnHomeData has accepted islam

**Comment by jakovmarkovanovic** [comment]
Wow

**Comment by Vorono4ka** [comment]
OwnHomeData left the chat!!!1!11
